
apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
data:
  tls.crt: MIIDBzCCAe+gAwIBAgIJAOgqvSN8hqRkMA0GCSqGSIb3DQEBBQUAMBoxGDAWBgNVBAMMD3p5cGVycy10ZXN0LmNvbTAeFw0xOTA3MTEyMDMyNDVaFw0yOTA3MDgyMDMyNDVaMBoxGDAWBgNVBAMMD3p5cGVycy10ZXN0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKTXtAjrhLbb2cvp4yCXa3O4JmtH3YU9L/hNWXD4owVPPtcpS2LeTQ49yAl2NzwnYW2BFyqIVPEgK4R8yNUAxb6SmT0Jczk1Pkx84FKp000a1OacvtED+MV7kP3TjP19gBZ9EJnHH7GXYLL56WoPFwWi0E5pOM4Li/btTfUTV5BwRavFhFWVzqInyPlRlJT+N/t8SsrR1nAxpOPVO4aFXFzQ1mj9LL2e0D5hJB+1Tfge64p8M66ABp+C8c7zgICA9xB0tS6xdC3oJrwiqattF1EJArNMcXa9EDQBSIgwbOS3prQipkVEjtoUw4WaRIJMORvQmbkmEdNXn0loV9oiQAkCAwEAAaNQME4wHQYDVR0OBBYEFFulrvSebo76zu4IpMYkKr4AuPAKMB8GA1UdIwQYMBaAFFulrvSebo76zu4IpMYkKr4AuPAKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAJHe92ANVJoaz/lbI1yUtyh5DNtd8Jh+g1FZ1HbQPAbG1fp2Tn76gXvfbvEvWJv2PC1ZyoOAZ7EfWqUVErfleraJDP2c+8h/cmuDLtNZEn6FivHUtwJiPCzAglsGBVS4JLzwXxmbv3ctAnSXxZ9lV8IQBqsI6FXQdYmuD12hggbc72roly9q8xm+TFyf1E3BONo3DgRF3VN0d3I2XZGOqLW/19f23trcluyUSkWbnsvG8eCaG0g0hUAIRrkFfxk8Q0mQBfVKk+5mckbAKEPcasgzZWn4g8HYND/0B15QhsCMsCyq160pGMc1zs7ATUnYnkna4IGI2+V5ywlpp6/d3KU=
  tls.key: MIIEowIBAAKCAQEApNe0COuEttvZy+njIJdrc7gma0fdhT0v+E1ZcPijBU8+1ylLYt5NDj3ICXY3PCdhbYEXKohU8SArhHzI1QDFvpKZPQlzOTU+THzgUqnTTRrU5py+0QP4xXuQ/dOM/X2AFn0QmccfsZdgsvnpag8XBaLQTmk4zguL9u1N9RNXkHBFq8WEVZXOoifI+VGUlP43+3xKytHWcDGk49U7hoVcXNDWaP0svZ7QPmEkH7VN+B7rinwzroAGn4LxzvOAgID3EHS1LrF0LegmvCKpq20XUQkCs0xxdr0QNAFIiDBs5LemtCKmRUSO2hTDhZpEgkw5G9CZuSYR01efSWhX2iJACQIDAQABAoIBAHlPnNirqqF/rgrY9yN3C8a/kNaGrsltPC45jkcLU72GkjJ521bJTl/aq6n6669DM/oIdGoCprBFAoGf65SF2wDilg9LMxa4zj4v8E4lWLF3u5JzbCIaECwVQaDq3Ol4QJlMNLlWx0ZEpw9Px60bqc+mADKUUQ+hg8GW5jYjo99Q8hAnWhp99R6USE5sGtUApH3FjPniuSk8yWwJFgv9bnqAwYw/QZEgLRD8LPsxWcCzPsoK5w3iqZyVRU5VYIcTuwEuBZySp3x79eFrCP1bEwhJzGxbF80I8ps595aRNqQOvECo/ASLf+pifLyMDGo3m/JT6v8g3yJcxRCEMK380QECgYEA1DnzeOkyfHY7k1LBRO7QBp5IQO3EjwJYdeZZZ4GPVm67hbUAsSFfeO600iceWEhpax8Zelz6q+LLMLwbR+36pNzJGwE9U1kTLTRS1aHZzusMyh2M+Nvw+IV0EYN2PuggROjr8PPaQev8u23fmcOYSM5grzu/WgvCItSBU0gX6tECgYEAxtfHGS6q2jBftyNvZ/bMszQm2YhhwQXNnpQ/IGpjG8884UupGMO9VA5/AxwQ4IzPP2bHr1iU+RNpjw3XSD/eY6utLgf/6rID2idMehEBjAuuzo20J2Hspy9vW+UZOiKRPpLj7DRHBZI+bEor2Pb3bCWQoHiPpqkQY2g7KbbWX7kCgYANmckorok1wL4AqwUHzeY3Bl3LC3HVWGki5ShFod/1whLydq8cqu7baTDdZvRi5AEdhFi1ps/JxDcRYHy/F1lAx4V73ZB4jvTTqM7GMiErSZUAPvSR3kaLJsJRfQNO9MFcqTC1uGr8XotL17bEu+w+fjtj/4g71RUT9lpzY+NkgQKBgHqVvl3NAnGfDvMlumHaqhn0ldrYFIPeIwSXmk9OpykW2w5+CZKF4eu3QCBXpiP5Sy9oGsUEFFt110blHoqhLWY/CXXuYpx7AJr2TVSXtV90OGGIxL7exPnQ6ZM6qxHHC8oK3s7Y78wEe81g8KVCpAidJAt6J/10DvFp6cduu7ypAoGBAJgecVOruMxE9TRZMquT1AX3Wa86XwubV176FeAzsab9f6pw+LyZ5HNGcICdHyyhBKCzlVotxST/NXJNDusX57mzecWkyxGc98EfFuJTLbfgJGaO/pLt3grFKKNvpUZfkWsFqJBN/fdD7R87ClRpiJibQDQWRYpRqtBvm6SX4yMW
kind: Secret
metadata:
  name: test-cert
  namespace: test
type: kubernetes.io/tls

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test
  labels: 
    app.kubernetes.io/name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts: 
     - zypers-test.com
    secretName: test-cert
  rules:
  - host: zypers-test.com
    http: 
      paths: 
      - path: /
        backend: 
          serviceName: nginx
          servicePort: 80



