
apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
data:
  tls.crt: MIIC+TCCAeGgAwIBAgIJAPiSPsRfNs5qMA0GCSqGSIb3DQEBBQUAMBMxETAPBgNVBAMMCHRlc3QuY29tMB4XDTE5MDcxMTE3MDAxNloXDTI5MDcwODE3MDAxNlowEzERMA8GA1UEAwwIdGVzdC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDfd851+sPnQjZ1icp9wifRLNywoG4bOqyLtngptMOkjjZ6ExaCUATBeIUq2lryrnk4B4ZS/71ykd/jSXB6mHnKUwu0KJQgA6drgXdsiw+ynhYQom5gGT1gt2GbYzLEVl5moQmnoq/19Sk7GWJxW+tISwu4zpq+U4mdo/2GgPtneskIS53HsHiRasUxlUvDFLzEQiCqGrgWjXsVOumm04L4cxEZ6bm5nN7OEB7rUs2cZaKx6hkw55Y2P/OAPCSsW6AVqMHdxzs+qOwuK402z0JuZ5fvkPDHcFgmDPhL4NfIU1nzF23FuZbep2JeXOQLbvlCl5ICYswc0NK1jiPqhoLvAgMBAAGjUDBOMB0GA1UdDgQWBBTUQd8GXppKrOuWHmpT7G8fvRo7IjAfBgNVHSMEGDAWgBTUQd8GXppKrOuWHmpT7G8fvRo7IjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQBp4px7S4zj1Ye6esGBGhE3f2sHWxAju2dLRTCQKyJN96Vq7k6emLmyID0qtMs2uYjF+VePVgsq0e8NMlOerHGzxMgb3D4qp/CqNSsw4tc2yOsgo7iJZr/v/6+mAoNEIrC6r3k6JqbUgtTdT7yBoNDrHBoVyTXxYP0pTWllpwy6MWkLumTxVVO/LUac0K1rtTjtSGlf1h86I49h3ZNhIXwfrNl6zI4CiJIhO2hkzXoB/n6aby7WVDC2bnzbP5+mgIJgWwbmsoi60g3hjbQA/kYx3HsVLlHbtXGOaR8fzndJpPFgBgbp5Wf83RFJyeujM26lYFUd5GHXenw3mas5C0y3
  tls.key: MIIEpAIBAAKCAQEA33fOdfrD50I2dYnKfcIn0SzcsKBuGzqsi7Z4KbTDpI42ehMWglAEwXiFKtpa8q55OAeGUv+9cpHf40lweph5ylMLtCiUIAOna4F3bIsPsp4WEKJuYBk9YLdhm2MyxFZeZqEJp6Kv9fUpOxlicVvrSEsLuM6avlOJnaP9hoD7Z3rJCEudx7B4kWrFMZVLwxS8xEIgqhq4Fo17FTrpptOC+HMRGem5uZzezhAe61LNnGWiseoZMOeWNj/zgDwkrFugFajB3cc7PqjsLiuNNs9CbmeX75Dwx3BYJgz4S+DXyFNZ8xdtxbmW3qdiXlzkC275QpeSAmLMHNDStY4j6oaC7wIDAQABAoIBAQCM0WBm9BiTGCRdOPFDAiA5Lf37x3za58RnXhqmnWRTw9IMZw7eGzKEAEBaWrLJDq0QY51/m+xzz/y3q0WX25GTr3VGl/OPoP3VPwZUfeTsd7YL0W+gWwdUdPqrAn2xP4PJRF1jJ5+ebFkJBtwD9xpyueevE3Jr0RR9JCPUqF7EO2tn6+AK6t/3Jc3de561EhRKenTghL19iq9ABPM7yygwcsGWsgUowFeuejZzBh9r70odHgpMx+tGaS+ET5nJs0fxerfZ1QA/Gc570CV+OteAoGRduw9KTH/sKmOTfuD+T6FHaeGEuh+KqWd7OetJci4/zQT8z41RvIPaQYBCCI2RAoGBAP/FeyxIQWrZ2wAZp9tdA+GLXXOSKtrE4HKxASJm1HAiBVXNye/5NtCZxFKSPuPbdN0b506d4ab3I4J+xWvRwUwjvvCnOzpVWZyCjnOwjdorFRZq58Sq7bUEo8ZH5Q2rQWdXiV5jDxqRZzQH8uxqxcqL8aFcgqkRolnqDU3ZOmgFAoGBAN+q7z1Mb7ezogmukzhITnblifdZgsCar1JKMHW7BCtM+2AEO3xGCVfEYfv/PZQ4vCsIpsRO8jJzz5N/zT63VlD9VwUxdWPB7zT0qDAC8w41nHCLhTNE0QbHcFzjM4Oc5hyqor7+t8yME4xlG+IooTNDdzunsdSoT5neAS+0rnVjAoGBAOF6h8aXAEyhN8aT1320N0qrYLwUvIDWFQQm9NgODPO5mjh1TbOnYOJu3DrqwFSBUDnocnbFCnv13TEabxJI/P4ReS+QTc90FKa8Fbb5i2QsnM+BeUbQZPQy3epb0RrGwcbHzcsOyu7iBjhBVa+DxVB1JJPbCTjg2d4oTog1m569AoGAOyXl/GzhQlAzsqHC9uhQL6sF8C5woGSHpphN9mRNdvH1q++Sl4uh3t7lFpHqA+94+1xfVZyW+facVyI98a7kGajVQV9R7t6TVoq4i3HMOt68jxqmT+eL62IEedvvfIeaZsxNG3saufH1HXSDiiw6bOcTeegf49/apRMLd0UtuYcCgYAMQsqxKWmYyOomx21BXnJZMLyfKjCQMYEbNG/+SQhfyuPrtEY1HOPCh4UPdpCIbzex3W9OemdyzMxsNFCKwlu2BPpvCcQaZax5Pzy3waTuNedkBlfl4ybyGhEN+nxXDM+m2QCzf7OOB2bsWrQ0LN5lyVsu1HI/VnJfgp5CmQI2eA==
kind: Secret
metadata:
  name: test-cert
  namespace: test
type: kubernetes.io/tls

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  labels: 
    app.kubernetes.io/name: test-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    
spec:
  tls:
  - hosts: 
     - test.com
    secretName: test-cert
  rules:
  - host: test.com
    http: 
      paths: 
      - path: /
        backend: 
          serviceName: nginx-service
          servicePort: 80



